language: node_js
node_js:
  - "10.15.0"

cache:
  directories:
    - node_modules

install:
  - yarn global add lerna jest now
  - lerna bootstrap

matrix:
  include:
    - name: "Server's Pipeline"
      env: PACKAGE_LOCATION=packages/server
    - name: "Client's Pipeline"
      env: PACKAGE_LOCATION=packages/client

script:
  - cd $PACKAGE_LOCATION
  - yarn test
  - yarn build

deploy:
  provider: script
  script: now public --token $NOW_TOKEN
  skip_cleanup: true