language: node_js
node_js:
  - 11 # current
  - 10 # lts

os:
  - linux
  - osx
  - windows

cache:
  yarn: true

# needed for windows travis, which gets stuck after running tests
# https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
  - YARN_GPG=no

# Travis uses yarn@1.3.2 on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

# install:
#   - yarn global add lerna jest now
#   - lerna bootstrap

# matrix:
#   include:
#     - name: "Server's Pipeline"
#       env: PACKAGE_LOCATION=packages/server
#     - name: "Client's Pipeline"
#       env: PACKAGE_LOCATION=packages/client

# script:
#   - cd $PACKAGE_LOCATION
#   - yarn test
#   - yarn build

# deploy:
#   provider: script
#   script: now public --token $NOW_TOKEN
#   skip_cleanup: true