language: node_js
node_js:
  - 11 # current
  - 10 # lts

cache:
  yarn: true

# Travis uses yarn@1.3.2 on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

deploy:
  script: now public --token $NOW_TOKEN
  skip_cleanup: true